### PR TITLE
created user authentication

### PR DESCRIPTION
**Pull request by claytonflesher**
You guys be sure and look over this closely. Make sure I didn't screw anything up.

It doesn't currently have rspec coverage. When I created the model in Devise, it overwrite what I had written in user_spec.rb.

### CODE REVIEW

**Comment by claytonflesher** [comment]
This fixes #3

**Comment by ajose01** [comment]
Thanks @Calvyn82 , let's have a live merge during tonight's call :)

**Comment by ravencovington** [comment]
Nice PR Calvyn. I would suggest having the devise gemfile and gemfile.lock in a separate commit to make things more cohesive.

**Comment by ajose01** [comment]
@Calvyn82 everything looks good :) thanks!

**Pull request merged**
