### PR TITLE
Added Vagrant to project for suckers like me and Tyler on Windows

### PR DESCRIPTION
**Pull request by ttilberg**
I'd like to package this vagrant setup with the project, since a few of us (at least Tyler and myself) have to work off Windows a fair amount of time, and we're just talking about a few lines of text/code if someone prefers to ignore it. Alternatively, feel free to reject this. There was talk in #slack about how this might be too far off-topic.

The image referenced in the Vagrantfile is based on `ubuntu/trusty64` but includes RVM, ruby 2.2.2, git and bundler set up and ready to go. I started maintaining this image for exploring Ruby, and also giving me a good baseline to start for some work projects that we are testing in .rb https://atlas.hashicorp.com/fitmentgroup/boxes/rvmruby222

On top of this starting image:
- Postgres is installed with user vagrant:vagrant
- Rails is installed (not currently locked to a particular version, that's easy to fix though)
- ports are forwarded:
  - 80 > 80
  - 3000 > 3000
  - 5432 > 5432

After loading Vagrant, you just need to cd to /vagrant/ruby-monday-blog/ and run the usual bundle install, rake db tasks.

### CODE REVIEW

**Comment by ajose01** [comment]
I love this idea. Let's review and talk about it with the group on the hangout tonight. Thanks!

**Comment by ttilberg** [comment]
Should we merge this, or let it set for now?

**Comment by ttilberg** [comment]
We all agree, this is better than baked beans. It is getting merged.

**Comment by claytonflesher** [comment]
We went over it in the Monday google hangout two weeks in a row. The general consensus is that it is a good idea for those that want and need it, and isn't a hindrance to anyone that doesn't.

Let's merge it.

**Comment by ttilberg** [comment]
Oh. Apparently it didn't get merged earlier. Oops. Trying again.

**Pull request merged**
