### PR TITLE
User Roles

### PR DESCRIPTION
**Pull request by ttilberg**
I extended Calvyn82's commit to include user roles via enum. More information on the implementation can be found here: http://railsapps.github.io/rails-authorization.html

### CODE REVIEW

**Comment by claytonflesher** [comment]
Thanks!

**Comment by sarony** [comment]
@ttilberg why do we need roles?

**Comment by farishkash** [comment]
We wanted an admin role for administration purposes vs a regular user/poster.

**Comment by sarony** [comment]
@farishkash Right, I'm asking why. What is the purpose of these roles? And you don't have two roles, you have three. So how were those roles chosen and what was the reasoning behind having them?

**Comment by farishkash** [comment]
I guess there's some confusion because I thought there was going to be two roles.  Just looked at the code I don't know why there would be a role for readers as the blog posts would be open to the public and commenting was going to use discus gem.  We only wanted Posters to post and edit and admins edit delete posts/posters as needed.  Maybe I missed something.

**Comment by claytonflesher** [comment]
I think we were going to have some kind of user role for commenters. I don't know how that will interact with Disqus and if it requires them to be users or not.

**Comment by ttilberg** [comment]
Okay, so it can just be edited. Or deleted. The original issue from Angel just said "add roles" and we decided to assign to me on Monday, so this was my interpretation. 

https://github.com/code-newbies/ruby-monday-blog/issues/12

Insert "I have no idea what I'm doing dog" pic here.

**Comment by farishkash** [comment]
@Calvyn82 it won't be necessary as Disqus has its own user system.  

@ttilberg Here is an updated version of the user stories that I had put up at our last Google Hangouts

```
As an Author we wish to 

write a post
tag a post
edit the post if I am the author of the post or admin/moderator of the blog

As a user I want to be able to 

View posts by author
View Posts by tag
sort posts by date ascending or descending
comment on post(unknown at the time but I believe it was decided on disqus gem)


Post should have
Created Date
An Author
A title
updated date(maybe)

As an admin

I want to be able to delete users
add users
edit other users posts
delete other users posts


```

**Comment by ttilberg** [comment]
So with regards to that, let's just pick what roles we want defined, and name them, and the enum can be updated.

So,
- `:admin`
- `:author` _default_ ?

or?

I originally had reader as a role because it seemed like there should be a completely unprivileged role set as default for people who register via the implementation that Calvin implemented. It also makes it easy to add other features later on that might require accountship of a "visitor" -- for instance, preferences, subscriptions, who knows. It just seemed like a very reasonable default, and is also very unobtrusive since it's just a tag in an enum. If it doesn't get used --- meh~

**Comment by farishkash** [comment]
@ttilberg This might actually lead to a better system, the reader role should be the default because it offers no permissions.  It might be better to then allow the admin to promote that user to author status.  Maybe another term than reader would be better, like user.

**Comment by ajose01** [comment]
Thanks for the user story @farishkash . We'll have a discussion on the hangout, and go from there. :+1:

**Comment by ajose01** [comment]
looks good! and no additional gems FTW :)

**Comment by ttilberg** [comment]
Angel helped me remerge existing origin/master into this branch to make sure everything was still legit. He's telling me to accept the pull. BUT PERHAPS SOMEONE ELSE SHOULD!! :0

**Comment by claytonflesher** [comment]
fixes #12

**Pull request merged**
