### PR TITLE
Post index order

### PR DESCRIPTION
**Pull request by claytonflesher**
Post index views and tag show views now list all posts in reverse order of when they were created, with most recent posts at the top.

### CODE REVIEW

**Comment by Calvyn82** [comment]
Solves Issue #46

**Comment by claytonflesher** [comment]
Solves Issue #45

**Comment by allanbreyes** [comment]
Not sure that the post data ordering belongs in the view.  Seems to fit better as a scope or method in the model or controller layers?

**Comment by claytonflesher** [comment]
I'll rewrite it when I get the chance.

**Comment by matugm** [comment]
I think we all should use the same title format for our PRs. Anyone disagree? We can just have the issue # in the description and that will automatically link it to the issue (if you go to issue #45 right now you will see a 'x referenced this issue from...').

So what I'm saying is to rename this to something like 'Change post index to descending order'.

**Comment by claytonflesher** [comment]
I changed my mind again, and moved it onto the models layer with an ordered_by_created_at method.

**Pull request merged**
