### PR TITLE
Resolves #69 - Add author's name on post

### LINKED ISSUE #69: Add post author's name to blog post
Add first & last name to blog post. "Written by first_name last_name"

### PR DESCRIPTION
**Pull request by abinoam**
Fixes #69.

I've had to begin this branch on top of the branches of @allanbreyes and @creativisionist as my patch depends on things done in these two branches. Before this PR get merged I may rebase it on top of what master will be.

### CODE REVIEW

**Comment by abinoam** [comment]
## Before

blogbefore

## After

blogwithauthorfullname

**Comment by allanbreyes** [comment]
Looks great!  Hey, maybe we can collapse the other two PRs and branches (#63 and #70)?  Otherwise... I'd love to see rebasing next Monday... I'm always hesitant to do rebasing b/c I'm afraid I'll nuke the git repo.  Would love to see you do it the right way, @abinoam!

**Comment by allanbreyes** [comment]
Fixes #69.

(If you put "Fixes #xx" it adds a link to close the issue once this PR is accepted.  Gotta love GitHub!)

**edit**: oops, I guess it needs to be in the base comment / PR body.  @abinoam I updated your base comment accordingly.

**Comment by abinoam** [comment]
Hi @allanbreyes , rebase is "tricky" the first times. But it's awesome when you get used to it.
I can do a rebase "live" next monday, sure.

**Comment by abinoam** [comment]
I thought "solves" worked also. But it happens that it is "resolves".

https://help.github.com/articles/closing-issues-via-commit-messages/
https://github.com/blog/1386-closing-issues-via-commit-messages

Thanks @allanbreyes !

**Comment by abinoam** [comment]
Will anybody merge it? I don't have the permissions to do it.

**Comment by allanbreyes** [comment]
Okay, I'm merging it!  (Don't shoot me.)

p.s. @ajose01 can you add @abinoam as collab?

**Pull request merged**
